export const decriptionContent = `
Welcome to my portfolio! I am thrilled to share my journey and expertise with you.\n
I am a passionate Full Stack Developer with a Bachelor's degree in Information Technology from Francis Xavier Engineering College, where I graduated with an impressive GPA of 8.7. My dedication to academic excellence was recognized with the Academic Topper Award in both 2018 and 2019.\n
In my professional journey spanning three years, I have honed my skills primarily in React Native mobile development, with a strong focus on frontend technologies including Redux, TypeScript, HTML, CSS, and SCSS. I am proficient in JavaScript and have leveraged my expertise to lead teams to success.\n
My career began as an intern at Centizen in 2021, where I swiftly progressed to the role of Junior Software Developer and later earned a promotion to Senior Software Developer for my exceptional contributions. Over the course of my employment, I led the development efforts for the ZenBasket ecommerce application between 2021 and 2023, stepping up as a team leader in 2022. This dual role allowed me to contribute as both a developer and a leader. Subsequently, I undertook the challenge of leading the ZenyoWorkforce project, a human resource management application, which was successfully completed in January 2024. Currently, I am at the helm of the ZenyoPayroll project, driving its development with my team.\n
My dedication to innovation and excellence has been acknowledged through various accolades, including the "Out of the Box Thinker" award in 2021, "Outstanding Contributor" award in 2022, and "Mr. Beyond Expectation" award in 2023, all bestowed by Centizen Inc. Additionally, my team's exceptional performance led to the receipt of the "Mission Possible Award" in 2023 for our rapid development of the ZenyoWorkforce mobile application.\n
With expertise in React Native, Redux, React, Next.js, Node.js, MongoDB, and PostgreSQL, I excel in leading teams and full stack development. My strengths lie in my ability to think creatively, collaborate effectively, and deliver projects with speed and elegance.\n
My short-term goal is to further explore various technologies and expand my skills as a Full Stack Developer, while my long-term aspiration is to leverage these skills to create groundbreaking applications that push the boundaries of innovation.\n
Beyond my professional endeavors, I am driven by a commitment to continuous learning and growth, constantly seeking opportunities to enhance my knowledge and contribute meaningfully to the IT world.\n
Thank you for taking the time to explore my portfolio. I look forward to the opportunity to collaborate with you on creating elegant applications.
`;
